import { DisasterInfo, QuizQuestion } from "../types/science";

export const DISASTERS_DATA: Record<string, DisasterInfo> = {
  earthquake: {
    id: "earthquake",
    name: "Earthquake Dynamics",
    subtitle: "Tectonic Strain & Seismic Wave Propagation",
    tagline:
      "When locked tectonic plates suddenly slip, releasing stored elastic potential energy.",
    color: "from-amber-600 to-orange-700",
    accentColor: "#f59e0b",
    overview:
      "Earth's crust is divided into massive tectonic plates that constantly glide over the ductile mantle. Where plates meet along fault lines, friction locks them in place while subterranean forces continue pushing. Once the accumulated elastic strain exceeds the fault friction, the rocks rupture violently, unleashing seismic energy that radiates in concentric waves through the lithosphere.",
    mechanism: [
      "Tectonic convection currents drag continental and oceanic plates toward or against each other.",
      "Friction along jagged fault boundaries locks the plate edges, causing tectonic stress to build over decades or centuries.",
      "The rock reaches its shear strength threshold and slips abruptly at the focus (hypocenter).",
      "Compressional Primary waves (P-waves) sprint outward first, followed by slower, destructive Secondary shear waves (S-waves) and rolling Surface waves (Rayleigh/Love waves).",
    ],
    keyTerms: [
      {
        term: "Hypocenter (Focus)",
        definition: "The exact underground point where rock fracture initiates.",
      },
      {
        term: "Epicenter",
        definition:
          "The geographic coordinate on Earth's surface situated directly above the focus.",
      },
      {
        term: "Moment Magnitude Scale (Mw)",
        definition:
          "Logarithmic scale measuring the total seismic energy released (each step is ~32x more energy).",
      },
      {
        term: "P-Waves & S-Waves",
        definition:
          "P-waves compress particles along travel direction; S-waves shake rock perpendicularly and cannot traverse liquids.",
      },
    ],
    safetyTips: [
      "Drop, Cover, and Hold On beneath a sturdy desk or table.",
      "Stay away from windows, heavy unanchored bookcases, and exterior brick walls.",
      "If outside, move to an open clear area away from utility wires, streetlights, and building facades.",
    ],
    variables: [
      {
        name: "magnitude",
        label: "Moment Magnitude (Mw)",
        min: 3.0,
        max: 9.2,
        step: 0.1,
        defaultValue: 6.8,
        unit: "Mw",
        description: "Logarithmic measure of total radiated seismic rupture energy.",
      },
      {
        name: "depth",
        label: "Focal Depth",
        min: 5,
        max: 70,
        step: 5,
        defaultValue: 15,
        unit: "km",
        description:
          "Depth beneath the surface. Shallow quakes (<20km) produce far more intense surface shaking.",
      },
      {
        name: "distance",
        label: "Distance from Epicenter",
        min: 10,
        max: 200,
        step: 5,
        defaultValue: 25,
        unit: "km",
        description: "Proximity to the rupture origin. Shaking attenuates with radial distance.",
      },
    ],
  },
  volcano: {
    id: "volcano",
    name: "Volcanic Eruption Mechanics",
    subtitle: "Magma Chambers, Volatiles & Eruptive Styles",
    tagline:
      "Molten rock buoyancy and dissolved gas expansion driving explosive and effusive volcanism.",
    color: "from-red-600 to-rose-700",
    accentColor: "#ef4444",
    overview:
      "Beneath active volcanoes, buoyant magma generated by subduction melting or mantle plumes accumulates within crustal reservoirs. As magma ascends, dropping lithostatic pressure causes dissolved volatile gases (H₂O, CO₂, SO₂) to exsolve into expanding bubbles. If the magma is viscous and silica-rich, trapped pressurized bubbles fragment explosively into ash plumes and pyroclastic surges; if fluid and basaltic, it erupts gently as glowing lava fountains.",
    mechanism: [
      "Partial melting of crustal or mantle rock produces molten magma that is less dense than surrounding solid rock.",
      "Magma gathers inside sub-surface chambers, heating surrounding rock and creating tectonic ground swelling.",
      "Dissolved volcanic gases (primarily water vapor and carbon dioxide) exsolve as overburden pressure drops.",
      "High gas content combined with high silica viscosity results in explosive Plinian eruptions; low viscosity produces effusive basaltic flows.",
    ],
    keyTerms: [
      {
        term: "Magma vs. Lava",
        definition:
          "Magma is molten rock stored under the surface; Lava is molten rock that has breached the Earth's surface.",
      },
      {
        term: "Viscosity",
        definition:
          "Resistance to flow; high-silica rhyolite is thick and sticky, while low-silica basalt flows easily.",
      },
      {
        term: "Pyroclastic Flow",
        definition:
          "A scalding avalanche of incandescent ash, pumice, and toxic gas traveling down slopes at over 200 km/h.",
      },
      {
        term: "VEI (Volcanic Explosivity Index)",
        definition: "Scale from 0 (gentle Hawaiian effusions) to 8 (mega-colossal supervolcanoes).",
      },
    ],
    safetyTips: [
      "Heed evacuation orders promptly upon seismic volcanic tremor alerts.",
      "Wear N95 respiratory masks and protective goggles to shield lungs and eyes from abrasive glass ash.",
      "Avoid low-lying river valleys prone to catastrophic volcanic mudflows (lahars).",
    ],
    variables: [
      {
        name: "magmaPressure",
        label: "Chamber Overpressure",
        min: 20,
        max: 100,
        step: 5,
        defaultValue: 75,
        unit: "MPa",
        description: "Gas pressure accumulated inside the upper crustal magma chamber.",
      },
      {
        name: "silicaContent",
        label: "Silica Content (Viscosity)",
        min: 45,
        max: 75,
        step: 1,
        defaultValue: 68,
        unit: "% SiO₂",
        description: "Controls magma stickiness (45% = fluid basalt, 75% = explosive rhyolite).",
      },
      {
        name: "gasContent",
        label: "Dissolved Volatiles",
        min: 1,
        max: 8,
        step: 0.5,
        defaultValue: 5.5,
        unit: "% wt",
        description:
          "Percentage of dissolved water vapor, CO₂, and sulfur gases in the magma melt.",
      },
    ],
  },
  tsunami: {
    id: "tsunami",
    name: "Tsunami Shoaling & Coastal Inundation",
    subtitle: "Megathrust Subduction Displacements & Ocean Wave Physics",
    tagline:
      "Massive water column vertical displacement transforming into crushing coastal surges.",
    color: "from-cyan-600 to-blue-800",
    accentColor: "#0284c7",
    overview:
      "Unlike wind-driven surface waves that only agitate the topmost meters of the ocean, a tsunami involves the kinetic movement of the entire water column from ocean floor to surface. When an undersea megathrust earthquake or volcanic caldera collapse rapidly heaves the ocean floor, billions of tons of seawater are displaced, propagating across deep oceans at jet-aircraft speeds before compressing violently at the shoreline.",
    mechanism: [
      "An underwater earthquake ruptures the seafloor, pushing seawater vertically upward or downward.",
      "Gravitational restoring forces launch long-wavelength gravity waves racing across the open ocean at 700–800 km/h with subtle wave heights (< 1m).",
      "As the wave approaches the continental shelf, friction with the shallowing seafloor slows the wave dramatically (shoaling).",
      "Wave kinetic energy compresses: wavelength shrinks from 200 km to < 10 km while wave height surges into a towering wall of water that floods miles inland.",
    ],
    keyTerms: [
      {
        term: "Shoaling Effect",
        definition:
          "The physics process where wave speed decreases in shallow water, forcing wave height to dramatically increase.",
      },
      {
        term: "Drawback",
        definition:
          "A rapid shoreline retreat of the sea exposing reefs, often the first warning of an incoming tsunami crest.",
      },
      {
        term: "Runup Height",
        definition:
          "The maximum ground elevation above normal sea level reached by tsunami floodwaters on land.",
      },
      {
        term: "DART Buoys",
        definition:
          "Deep-ocean Assessment and Reporting of Tsunamis pressure sensors detecting ocean floor displacement.",
      },
    ],
    safetyTips: [
      "If you feel strong ground shaking near a coast, or observe seawater rapidly receding, evacuate to high ground immediately!",
      "Never visit the beach to watch a tsunami wave arrive—tsunamis travel faster than a person can sprint.",
      "Wait for official all-clear notifications, as subsequent tsunami waves can arrive hours later and be even larger.",
    ],
    variables: [
      {
        name: "seafloorDisplacement",
        label: "Seafloor Vertical Thrust",
        min: 2,
        max: 20,
        step: 1,
        defaultValue: 12,
        unit: "meters",
        description: "Vertical offset of the ocean plate along the subduction rupture fault.",
      },
      {
        name: "oceanDepth",
        label: "Open Ocean Depth",
        min: 2000,
        max: 6000,
        step: 500,
        defaultValue: 4500,
        unit: "m",
        description:
          "Depth of the abyssal plain. Wave speed is mathematically proportional to sqrt(g × depth).",
      },
      {
        name: "coastalSlope",
        label: "Coastal Slope Steepness",
        min: 1,
        max: 10,
        step: 1,
        defaultValue: 4,
        unit: "°",
        description:
          "Gentle slopes amplify overland runup distance; steep cliffs cause violent localized wave reflections.",
      },
    ],
  },
  hurricane: {
    id: "hurricane",
    name: "Tropical Cyclone Thermodynamics",
    subtitle: "Latent Heat Engine, Coriolis Rotation & Eyewall Physics",
    tagline: "Colossal atmospheric heat engines fueled by warm tropical ocean evaporation.",
    color: "from-sky-500 to-indigo-700",
    accentColor: "#38bdf8",
    overview:
      "Tropical cyclones (hurricanes, typhoons, cyclones) are enormous thermodynamic heat engines that convert thermal energy stored in warm tropical sea surfaces into ferocious rotational kinetic winds. Warm ocean waters (> 26.5°C) evaporate moisture into ascending air parcels. As this vapor rises and condenses into torrential rain clouds, it liberates enormous latent heat, further lowering central barometric pressure and drawing in spiraling air steered by planetary Coriolis deflection.",
    mechanism: [
      "Warm ocean water (>26.5°C) provides intense moisture evaporation into the lower troposphere.",
      "Low vertical wind shear allows thunderstorms to organize vertically into a cohesive rotating convective cluster.",
      "The planetary Coriolis effect imparts cyclonic rotation (counter-clockwise in Northern Hemisphere, clockwise in Southern).",
      "As warm air accelerates inward toward the lowest pressure, centrifugal force creates a calm clear eye surrounded by a vicious eyewall.",
    ],
    keyTerms: [
      {
        term: "The Eye & Eyewall",
        definition:
          "The eye is a calm, low-pressure core; the surrounding eyewall contains the fiercest winds and heaviest rain.",
      },
      {
        term: "Storm Surge",
        definition:
          "An abnormal rise of ocean water pushed ashore by cyclonic winds, often causing up to 90% of cyclone casualties.",
      },
      {
        term: "Latent Heat of Condensation",
        definition:
          "Energy released when moisture vapor condenses into clouds, fueling the storm's power engine.",
      },
      {
        term: "Saffir-Simpson Scale",
        definition:
          "Category 1 (119–153 km/h) through Category 5 (≥ 252 km/h) measuring sustained wind velocities.",
      },
    ],
    safetyTips: [
      "Board windows with storm shutters or heavy plywood; secure outdoor furniture and projectiles.",
      "Obey mandatory coastal evacuation zones ahead of deadly storm surges.",
      "Stay indoors in an interior windowless room during the eyewall; do not mistake the calm eye for the end of the storm.",
    ],
    variables: [
      {
        name: "seaTemp",
        label: "Sea Surface Temperature",
        min: 24,
        max: 32,
        step: 0.5,
        defaultValue: 29.5,
        unit: "°C",
        description:
          "Threshold of 26.5°C is needed. Warmer waters supercharge storm intensification.",
      },
      {
        name: "centralPressure",
        label: "Central Barometric Pressure",
        min: 880,
        max: 1010,
        step: 5,
        defaultValue: 925,
        unit: "hPa",
        description:
          "Lower atmospheric pressure in the eye creates steeper pressure gradients and higher winds.",
      },
      {
        name: "windShear",
        label: "Vertical Wind Shear",
        min: 5,
        max: 40,
        step: 5,
        defaultValue: 10,
        unit: "knots",
        description:
          "High wind shear rips storm cloud tops away; low wind shear allows vertical intensification.",
      },
    ],
  },
  flood: {
    id: "flood",
    name: "Hydrological Flood Dynamics",
    subtitle: "Precipitation, Infiltration Capacity & River Basin Inundation",
    tagline: "When precipitation rate outpaces soil infiltration and drainage network capacities.",
    color: "from-blue-600 to-teal-700",
    accentColor: "#0d9488",
    overview:
      "Flooding represents a critical imbalance in the terrestrial hydrological cycle. When torrential rainfall, rapid snowmelt, or storm surge delivers water faster than the ground can absorb it or rivers can convey it, surplus runoff accumulates overland. Urbanization with asphalt and concrete surfaces severely reduces soil infiltration, transforming natural watershed buffers into rapid, dangerous flash flood channels.",
    mechanism: [
      "Heavy prolonged rainfall or sudden cloudburst precipitation saturates upper soil horizons.",
      "Once soil infiltration capacity is exceeded, excess water becomes surface runoff directed into stream tributaries.",
      "Hydrograph peaks: river stage elevates until bankfull capacity is breached, overflowing into natural floodplains.",
      "Impervious surfaces (concrete, asphalt) accelerate runoff velocities by eliminating natural vegetative absorption.",
    ],
    keyTerms: [
      {
        term: "Infiltration Capacity",
        definition: "The maximum rate at which a given soil texture can absorb surface water.",
      },
      {
        term: "Floodplain",
        definition:
          "Low-lying flat land adjacent to a river that naturally receives excess overflow waters.",
      },
      {
        term: "Hydrograph Lag Time",
        definition:
          "The delay between peak rainfall and peak river discharge; urban areas drastically shorten this lag.",
      },
      {
        term: "Flash Flood",
        definition:
          "A rapid and extreme flow of high water into a normally dry area occurring within minutes to 6 hours.",
      },
    ],
    safetyTips: [
      "Turn Around, Don't Drown! Just 15 cm of moving water can knock down an adult, and 30 cm can float most cars.",
      "Never attempt to drive or walk through flooded roadways or obscured bridges.",
      "Move valuables and electrical appliances to higher floors if living in low-lying riparian zones.",
    ],
    variables: [
      {
        name: "rainfallIntensity",
        label: "Rainfall Rate",
        min: 10,
        max: 120,
        step: 5,
        defaultValue: 65,
        unit: "mm/hr",
        description: "Rate of incoming precipitation over the drainage basin.",
      },
      {
        name: "soilSaturation",
        label: "Initial Soil Saturation",
        min: 10,
        max: 100,
        step: 5,
        defaultValue: 80,
        unit: "%",
        description:
          "Antecedent moisture condition; pre-saturated soils cannot absorb additional water.",
      },
      {
        name: "urbanization",
        label: "Impervious Ground Cover",
        min: 0,
        max: 85,
        step: 5,
        defaultValue: 45,
        unit: "% paved",
        description:
          "Percentage of drainage basin covered with non-absorbent asphalt and concrete.",
      },
    ],
  },
  wildfire: {
    id: "wildfire",
    name: "Wildfire Combustion & Behavior",
    subtitle: "The Fire Triangle, Fuel Moisture & Topographic Propagation",
    tagline:
      "Self-sustaining rapid exothermic combustion propelled by wind, heat, and dried biomass.",
    color: "from-amber-700 to-red-800",
    accentColor: "#ea580c",
    overview:
      "A wildfire is an uncontrolled combustion reaction consuming forest fuels and brush. Propagation is dictated by the Fire Environment Triangle: Fuel, Weather, and Topography. Dry atmospheric conditions desiccate dead and living plant biomass. High winds supply fresh oxygen while tilting flames forward to preheat unburned fuel ahead of the fireline. Fires also travel exponentially faster uphill because convective heat rises directly into upslope vegetation.",
    mechanism: [
      "Preheating: Radiant and convective heat dries nearby vegetation, driving off moisture until ignition temperature (~300°C) is reached.",
      "Flaming combustion: Thermal pyrolysis breaks wood cellulose into flammable hydrocarbon gases that burn with open flames.",
      "Wind steering: Strong winds supply oxygen and cast airborne glowing embers (spot fires) kilometers ahead of the main fire perimeter.",
      "Topographic chimney effect: Slopes channel convective heat upward, dramatically accelerating uphill spread rates.",
    ],
    keyTerms: [
      {
        term: "The Fire Triangle",
        definition:
          "The three elements required for combustion: Fuel (wood, grass), Oxygen, and Heat (ignition source).",
      },
      {
        term: "Fuel Moisture Content",
        definition:
          "The percentage of water weight in vegetation; fuels below 10% moisture burn explosively.",
      },
      {
        term: "Crown Fire vs. Surface Fire",
        definition:
          "Surface fires burn leaf litter and grass; crown fires leap between forest tree canopies and are almost impossible to stop directly.",
      },
      {
        term: "Firebreak",
        definition:
          "A cleared gap in vegetation that deprives advancing fires of continuous combustible fuel.",
      },
    ],
    safetyTips: [
      "Create a 30-meter defensible clearance zone of pruned, irrigated vegetation around homes in wildland interfaces.",
      "Pack an emergency Go-Bag with essentials, N95 smoke masks, and follow evacuation advisories early.",
      "Never park vehicles over dry grass, as hot catalytic converters can ignite instantaneous grass fires.",
    ],
    variables: [
      {
        name: "windSpeed",
        label: "Wind Velocity",
        min: 0,
        max: 70,
        step: 5,
        defaultValue: 35,
        unit: "km/h",
        description: "Winds supply fresh oxygen and bend flame tips toward fuel ahead.",
      },
      {
        name: "fuelMoisture",
        label: "Vegetation Fuel Moisture",
        min: 4,
        max: 30,
        step: 1,
        defaultValue: 8,
        unit: "% moisture",
        description: "Moisture content of brush. Below 10% triggers extreme fire behavior.",
      },
      {
        name: "slopeAngle",
        label: "Terrain Slope Angle",
        min: 0,
        max: 45,
        step: 5,
        defaultValue: 20,
        unit: "° uphill",
        description:
          "Fire spreads twice as fast on a 20° slope compared to flat terrain due to convective preheating.",
      },
    ],
  },
};

export const DISASTERS_QUIZ: QuizQuestion[] = [
  {
    id: "dis-q1",
    labId: "disasters",
    type: "multiple-choice",
    question:
      "What is the difference between an earthquake's epicenter and its hypocenter (focus)?",
    options: [
      "The hypocenter is deep underground where rupture starts; the epicenter is on Earth's surface directly above it",
      "The epicenter is underground and the hypocenter is in the atmosphere",
      "Epicenter only applies to volcanoes, while hypocenter applies to tsunamis",
      "They are identical terms measuring earthquake duration",
    ],
    correctIndex: 0,
    explanation:
      "The hypocenter (or focus) is the underground physical location along the fault plane where rock fracture begins. The epicenter is the geographic spot on the surface straight above it.",
    concept: "Earthquake Anatomy",
  },
  {
    id: "dis-q2",
    labId: "disasters",
    type: "multiple-choice",
    question: "Why does a tsunami wave grow dramatically taller as it approaches the shoreline?",
    options: [
      "The gravitational pull of the moon increases near beaches",
      "The wave catches fire from underwater volcanic heat",
      "Shoaling: shallow water slows the wave speed, compressing energy and forcing wave height to surge upward",
      "Coastal winds blow the water backward",
    ],
    correctIndex: 2,
    explanation:
      "This is called the shoaling effect. In deep water, tsunamis move at 800 km/h with low height. As water shallows, friction slows the wave front, compressing the wavelength and forcing water into a massive vertical surge.",
    concept: "Tsunami Shoaling Effect",
  },
  {
    id: "dis-q3",
    labId: "disasters",
    type: "true-false",
    question:
      "Magma and lava are two names for the exact same physical state and location of molten rock.",
    options: [
      "True",
      "False - Magma is underground beneath the surface; Lava is molten rock that has breached the surface",
    ],
    correctIndex: 1,
    explanation:
      "Geologists distinguish molten rock: when it is trapped beneath Earth's crust with dissolved gases under pressure, it is 'magma'; once it erupts onto the surface and degasses, it is 'lava'.",
    concept: "Volcanic Geology",
  },
  {
    id: "dis-q4",
    labId: "disasters",
    type: "predict-outcome",
    question:
      "What primary fuel source powers the tremendous rotational energy of a tropical hurricane?",
    options: [
      "Latent heat released when evaporated moisture from warm ocean water (>26.5°C) condenses into storm clouds",
      "Underwater geothermal vents",
      "Solar radiation striking cloud tops",
      "Magnetic field lines crossing the equator",
    ],
    correctIndex: 0,
    explanation:
      "Warm tropical ocean water evaporates rapidly. As rising warm, moist air cools and condenses into clouds, it releases massive latent heat of condensation, which lowers atmospheric pressure and acts as the engine of the cyclone.",
    concept: "Hurricane Thermodynamics",
  },
  {
    id: "dis-q5",
    labId: "disasters",
    type: "multiple-choice",
    question:
      "Why do urbanized cities with lots of asphalt and concrete suffer worse flash floods than natural forested wetlands during the same rainstorm?",
    options: [
      "Concrete attracts rain clouds magnetically",
      "Impervious surfaces prevent water infiltration into soil, turning nearly 100% of rainfall into rapid surface runoff",
      "Paved roads are lower than sea level everywhere",
      "City drains create extra water out of nowhere",
    ],
    correctIndex: 1,
    explanation:
      "Soil and vegetation act like natural sponges that absorb rain. Impervious surfaces like pavement and buildings prevent infiltration, speeding up runoff into storm channels and creating dangerous flash flood spikes.",
    concept: "Hydrology & Impervious Surfaces",
  },
  {
    id: "dis-q6",
    labId: "disasters",
    type: "predict-outcome",
    question:
      "Why does a wildfire spread significantly faster moving uphill along a mountain ridge than downhill?",
    options: [
      "Oxygen is denser at mountain peaks",
      "Rising convective heat and flames tilt forward, preheating and drying vegetation higher up the slope before the fire arrives",
      "Gravity pulls flames uphill",
      "Wind only blows upward on mountains",
    ],
    correctIndex: 1,
    explanation:
      "Hot air and flames rise naturally. On an uphill slope, the rising heat directly envelops the vegetation just above the fire, baking off moisture and preheating the fuel so it ignites almost instantly.",
    concept: "Wildfire Topographic Behavior",
  },
  {
    id: "dis-q7",
    labId: "disasters",
    type: "multiple-choice",
    question:
      "If you feel strong ground shaking while on a coastal beach, or see the ocean tide suddenly retreat very far out, what is the safest immediate action?",
    options: [
      "Walk out onto the exposed seabed to collect shells",
      "Wait for a siren to sound on television",
      "Immediately evacuate on foot to high ground or inland as fast as possible",
      "Hide inside a beach cabana",
    ],
    correctIndex: 2,
    explanation:
      "A receding tide (drawback) is nature's strongest warning of an incoming tsunami crest. You must move to high ground immediately, without waiting for official warnings.",
    concept: "Tsunami Warning Signs & Safety",
  },
  {
    id: "dis-q8",
    labId: "disasters",
    type: "multiple-choice",
    question: "Which type of volcanic eruption is typically the most dangerous and explosive?",
    options: [
      "Basaltic lava fountain with low silica and gentle degassing",
      "Viscous, high-silica magma with high trapped gas content producing pyroclastic flows and ash clouds",
      "Deep submarine pillow lava spreading",
      "Mud pots bubbling in a hot spring",
    ],
    correctIndex: 1,
    explanation:
      "High silica content makes magma thick and sticky (viscous), preventing gas bubbles from escaping easily. As pressure mounts, the bubbles violently fragment the magma into abrasive ash, pumice, and deadly pyroclastic surges.",
    concept: "Volcanic Viscosity & Explosivity",
  },
];
